import logo from "../assets/logo.svg"
import call_icon from "../assets/call_icon.svg"
import mail_icon from "../assets/mail_icon.svg"
import dotted_bg from "../assets/dotted_bg.svg"
import hero1 from "../assets/hero_img1.png"
import hero_services_access_control from "../assets/services_access_control_icon.svg"
import hero_services_energy_saving from "../assets/services_energy_saving_icon.svg"
import hero_services_amc_services from "../assets/services_amc_services_icon.svg"
import hero_services_remote_monitoring from "../assets/services_remote_monitoring_icon.svg"
import light_red_bg from "../assets/light-red-bg.png"
import product_access_control from "../assets/product_access_control.png"
import video_img from "../assets/video-img.png"
import idea from "../assets/idea.svg"
import emphasize from "../assets/empathize.svg"
import build from "../assets/build.svg"
import deploy from "../assets/deploy.svg"
import brand1 from "../assets/brand1.png"
import brand2 from "../assets/brand2.png"
import brand3 from "../assets/brand3.png"
import brand4 from "../assets/brand4.png"
import brand5 from "../assets/brand5.png"
import brand6 from "../assets/brand6.png"
import brand7 from "../assets/brand7.png"
import dotted_bg_short from "../assets/dotted_bg_short.png"
import partner1 from "../assets/partner1.svg"
import partner2 from "../assets/partner2.svg"
import partner3 from "../assets/partner3.svg"
import partner4 from "../assets/partner4.svg"


export default { logo, call_icon, mail_icon, dotted_bg, hero1, hero_services_access_control, hero_services_energy_saving, hero_services_amc_services, hero_services_remote_monitoring, light_red_bg, product_access_control, video_img, idea, emphasize, build, deploy, brand1, brand2, brand3, brand4, brand5, brand6, brand7, dotted_bg_short, partner1, partner2, partner3, partner4 }